### PR TITLE
Fix for Ghidra 9.2.2+

### PR DESCRIPTION
**Pull request by encounter**

### CODE REVIEW

**Comment by Adubbz** [comment]
Thanks for this. I made the change manually since I noticed there was some weirdness going on with the ``gradlew`` file in this PR and realised it was probably not worth making you mess around to fix it.

**Comment by encounter** [comment]
That's ok, but the gradlew change was intentional to make it executable on *nix.

**Comment by Adubbz** [comment]
Ah okay, it wasn't obvious that was what was changed based on the diff. My bad then!

**Comment by encounter** [comment]
No worries, I should have mentioned it.

**Pull request closed without merging**
