### PR TITLE
Add support for 17.0.0 (64-bit only)

### LINKED ISSUE #41: NSO Loader: Index 0 out of bounds for length 0
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at adubbz.nx.loader.common.NXProgramBuilder.setupRelocations(NXProgramBuilder.java:270)
	at adubbz.nx.loader.common.NXProgramBuilder.load(NXProgramBuilder.java:117)
	at adubbz.nx.loader.SwitchLoader.loadProgramInto(SwitchLoader.java:164)
	at ghidra.app.util.opinion.AbstractProgramLoader.loadInto(AbstractProgramLoader.java:171)
	at adubbz.nx.loader.SwitchLoader.loadProgram(SwitchLoader.java:117)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:132)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2023-Apr-05 1559 BST
Ghidra Version: 10.3
Java Home: /usr/lib/jvm/java-17-openjdk
JVM Version: N/A 17.0.7
OS: Linux 6.3.0-asahi-8-1-edge-ARCH aarch64
```

Sorry for the vagueness, I'm down a rabbithole rn so I'll circle back and provide more details later

### PR DESCRIPTION
**Pull request by TSRBerry**
This PR adds support for read-only relocations which were added in 17.0.0 binaries.

These changes were ported from SciresM's changes to `nxo64.py`/`ipcserver.py` [here](https://github.com/SciresM/switch-reversing/tree/1700_support), which is why I added him as a co-author to these commits.

The nxo64 changes are already done, but I need to figure out how to port the ipcserver changes, since they involve  reading values from the `IPCEmulator` and I'm currently trying to understand how this could be done here. I currently think the emulator is set up in one function and only used there, which differs from the way ipcserver seems to handle it.

I'll mark this PR as draft until I either figure this out or somebody else figures it out before me and wants to add the solution here.

---

Aside from these changes I made a minor adjustment to the way plt entries are handled, so no exceptions can be thrown there and the user instead just receives a note about missing support for CFI-enabled binaries.

This closes #41, but doesn't solve the underlying issue that we currently can't find the plt for the binaries mentioned above.

### CODE REVIEW

**Comment by Adubbz** [comment]
I would actually support IPCEmulator being removed (unless someone actually does rely upon it). I don't think it has been completely functional since much earlier versions of HOS,and the value added was fairly limited to begin with

**Comment by TSRBerry** [comment]
Maybe I should try making [nxo-utils/ipcserver.py](https://github.com/TSRBerry/nxo-utils/blob/master/ipcserver.py) compatible with Ghidra instead if you want to replace IPCEmulator entirely.

I have the ipcserver changes almost done already, but I'm currently running into a few bugs that I need to fix before I can push that.

I should check if we are able to make analyzers in python as well or if these scripts need to be ported to Java.

**Comment by Adubbz** [comment]
Where possible porting to Java remains ideal in my mind, given Ghidra continues to only package outdated Python 2/Jython support

**Comment by TSRBerry** [comment]
I tested these changes with ghidra version 10.4 and the ldn sysmodule for 16.1.0 and 17.0.0 and compared the results against `ipcserver.py`.

I'd say this is working correctly now and is ready for review!

The `build.gradle` changes made working on this a lot easier since I could just launch ghidra from within the project and I didn't have to restart it twice to install a new extension as I needed to do before.

**Pull request merged**
